version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "monthly"
    directory: /
    allow:
      - dependency-name: "Submodules/AMReX"
      - dependency-name: "Submodules/RRTMGP"
      - dependency-name: "Submodules/WW3"
      - dependency-name: "Submodules/YAKL"
